import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";


export default function Home() {
  return (
      <div className={styles.container} >
        <Navbar />
        <Head>
          <title>Joseph Ayman</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            HI, I'M JOSEPH AYMAN, <br />
            A SOFTWARE DEVELOPER <br />
            BASED IN OSLO, NORWAY.
          </h1>
          <p>Welcome to my piece of the internet.</p>
          <p className={styles.description}>Site in progress...</p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
  );
}
